import ollama
import json
import os

SYSTEM_PROMPT = open("audit_prompt.txt").read()

def load_evaluation_payload(filepath="evaluation_result.json"):
    """Load evaluation payload from JSON file generated by analyze_repo.py"""
    if not os.path.exists(filepath):
        raise FileNotFoundError(
            f"'{filepath}' not found. Run 'python analyze_repo.py' first."
        )
    
    with open(filepath, "r") as f:
        return json.load(f)


def run_ai_audit(evaluation_payload):
    """Run AI audit on evaluation results.
    
    This function:
    - Does not allow score manipulation
    - Forces structured JSON response
    - Keeps AI boxed in to audit role only
    """
    response = ollama.chat(
        model="qwen2.5-coder:7b",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": json.dumps(evaluation_payload, indent=2)
            }
        ]
    )

    return response["message"]["content"]


if __name__ == "__main__":
    # Load evaluation payload from analyze_repo.py output
    try:
        evaluation_payload = load_evaluation_payload()
        
        print("Loaded evaluation from: evaluation_result.json")
        print(f"Final Score: {evaluation_payload['evaluation_summary']['final_score']}")
        print(f"Confidence: {evaluation_payload['evaluation_summary']['confidence']}")
        print("\nRunning AI audit...")
        print("=" * 50)
        
        result = run_ai_audit(evaluation_payload)
        print(result)
        
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("\nUsage:")
        print("  1. First run: python analyze_repo.py")
        print("  2. Then run:  python ai_audit.py")
